import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/app/hooks/AuthProvider";
import { Toaster } from "sonner";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  // eslint-disable-next-line no-undef
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en"  >
      <body>

        {children}
        <Toaster/>
        

      </body>
    </html>
    </AuthProvider>
  );
}
