import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/app/hooks/AuthProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "./hooks/Tfemeprovider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en"  suppressHydrationWarning>
      <body>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
        <Toaster/>
        </ThemeProvider>

      </body>
    </html>
    </AuthProvider>
  );
}
